server:
  port: 8090
  forward-headers-strategy: framework
  use-forward-headers: true
  tomcat:
    remote-ip-header: X-Forwarded-For
    protocol-header: X-Forwarded-Proto
    protocol-header-https-value: https
    port-header: X-Forwarded-Port
    port-header-https-value: 443
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23lic6yRkPpP5wURtt
            client-secret: 9714ad8b5d697f118b7ca4b32745ecaf926239bd

# Swagger configuration for development
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
